version: '3.9'
services:
  argo-nezha:
    image: yutian81/argo-nezha-v1:latest
    container_name: argo-nezha-v1
    pull_policy: always
    restart: always
    ports:
      - "8443:8443"  # 映射主机9443端口到容器443端口
    env_file: .env  # 推荐使用 .env 文件管理变量
    volumes:
      - ./dashboard:/dashboard/data  # 挂载数据卷（可选，持久化数据）
